name: "ci airflow action"
description: "Test Airflow DAGs at PR time"
author: "Datacoves"

inputs:
  command:
    description: "command"
    default: "dbt run"
    required: false
  dbt_project_folder:
    description: "dbt project folder. Defaults to ."
    default: "."
    required: false
outputs:
  result:
    description: "Success or failure of the dbt command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
branding:
  icon: "database"
  color: "purple"
